export const MOCK_DATA = [
  {
    id: 1,
    name: "Laptop",
    price: 999.99,
    category: "Electronics",
    rating: 4.5,
    stock: "In Stock",
    manufacturer: "BrandA",
    releaseDate: "2022-01-15",
    reviews: 120,
  },
  {
    id: 2,
    name: "Smartphone",
    price: 699.99,
    category: "Electronics",
    rating: 4.0,
    stock: "Out of Stock",
    manufacturer: "BrandB",
    releaseDate: "2021-11-20",
    reviews: 250,
  },
  {
    id: 3,
    name: "Tablet",
    price: 399.99,
    category: "Electronics",
    rating: 4.2,
    stock: "In Stock",
    manufacturer: "BrandA",
    releaseDate: "2022-03-05",
    reviews: 80,
  },
  {
    id: 4,
    name: "Headphones",
    price: 199.99,
    category: "Accessories",
    rating: 3.8,
    stock: "In Stock",
    manufacturer: "BrandC",
    releaseDate: "2021-12-10",
    reviews: 60,
  },
  {
    id: 5,
    name: "Keyboard",
    price: 49.99,
    category: "Accessories",
    rating: 4.1,
    stock: "In Stock",
    manufacturer: "BrandC",
    releaseDate: "2020-06-18",
    reviews: 150,
  },
  {
    id: 6,
    name: "Monitor",
    price: 299.99,
    category: "Electronics",
    rating: 4.3,
    stock: "In Stock",
    manufacturer: "BrandB",
    releaseDate: "2022-05-25",
    reviews: 45,
  },
  {
    id: 7,
    name: "Mouse",
    price: 29.99,
    category: "Accessories",
    rating: 4.0,
    stock: "Out of Stock",
    manufacturer: "BrandA",
    releaseDate: "2021-02-10",
    reviews: 200,
  },
  {
    id: 8,
    name: "Camera",
    price: 599.99,
    category: "Electronics",
    rating: 4.7,
    stock: "In Stock",
    manufacturer: "BrandD",
    releaseDate: "2021-08-14",
    reviews: 180,
  },
  {
    id: 9,
    name: "Printer",
    price: 149.99,
    category: "Electronics",
    rating: 3.9,
    stock: "In Stock",
    manufacturer: "BrandB",
    releaseDate: "2021-05-22",
    reviews: 75,
  },
  {
    id: 10,
    name: "Smartwatch",
    price: 199.99,
    category: "Electronics",
    rating: 4.2,
    stock: "Out of Stock",
    manufacturer: "BrandA",
    releaseDate: "2022-02-18",
    reviews: 95,
  },
  {
    id: 11,
    name: "Speakers",
    price: 129.99,
    category: "Accessories",
    rating: 3.5,
    stock: "In Stock",
    manufacturer: "BrandC",
    releaseDate: "2021-10-09",
    reviews: 110,
  },
  {
    id: 12,
    name: "Webcam",
    price: 79.99,
    category: "Electronics",
    rating: 4.0,
    stock: "In Stock",
    manufacturer: "BrandD",
    releaseDate: "2022-04-11",
    reviews: 50,
  },
  {
    id: 13,
    name: "Router",
    price: 89.99,
    category: "Electronics",
    rating: 4.1,
    stock: "Out of Stock",
    manufacturer: "BrandB",
    releaseDate: "2021-09-07",
    reviews: 135,
  },
  {
    id: 14,
    name: "External Hard Drive",
    price: 59.99,
    category: "Accessories",
    rating: 3.9,
    stock: "In Stock",
    manufacturer: "BrandA",
    releaseDate: "2021-06-30",
    reviews: 140,
  },
  {
    id: 15,
    name: "Charger",
    price: 19.99,
    category: "Accessories",
    rating: 4.3,
    stock: "In Stock",
    manufacturer: "BrandC",
    releaseDate: "2022-01-03",
    reviews: 85,
  },
  {
    id: 16,
    name: "Memory Card",
    price: 14.99,
    category: "Accessories",
    rating: 4.5,
    stock: "Out of Stock",
    manufacturer: "BrandD",
    releaseDate: "2021-12-25",
    reviews: 210,
  },
  {
    id: 17,
    name: "USB Cable",
    price: 9.99,
    category: "Accessories",
    rating: 3.6,
    stock: "In Stock",
    manufacturer: "BrandA",
    releaseDate: "2020-11-12",
    reviews: 75,
  },
  {
    id: 18,
    name: "Power Bank",
    price: 39.99,
    category: "Accessories",
    rating: 4.4,
    stock: "In Stock",
    manufacturer: "BrandB",
    releaseDate: "2021-03-21",
    reviews: 65,
  },
  {
    id: 19,
    name: "VR Headset",
    price: 499.99,
    category: "Electronics",
    rating: 4.6,
    stock: "Out of Stock",
    manufacturer: "BrandD",
    releaseDate: "2022-06-17",
    reviews: 170,
  },
  {
    id: 20,
    name: "Gaming Chair",
    price: 229.99,
    category: "Accessories",
    rating: 4.0,
    stock: "In Stock",
    manufacturer: "BrandC",
    releaseDate: "2022-02-28",
    reviews: 190,
  },
];
